import { Page } from './Page';
import { Section } from './Section';
import { Column } from './Column';
import { Text } from './Text';
import { Image } from './Image';
import { Group } from './Group';
import { Button } from './Button';
import { Divider } from './Divider';
import { Wrapper } from './Wrapper';
import { Spacer } from './Spacer';
import { Raw } from './Raw';
import { Accordion } from './Accordion';
import { AccordionElement } from './AccordionElement';
import { AccordionTitle } from './AccordionTitle';
import { AccordionText } from './AccordionText';
import { Carousel } from './Carousel';
import { Hero } from './Hero';
import { Navbar } from './Navbar';
import { Social } from './Social';
import { Table } from './Table';
export declare const blocks: {
    page: typeof Page;
    section: typeof Section;
    column: typeof Column;
    text: typeof Text;
    image: typeof Image;
    group: typeof Group;
    button: typeof Button;
    divider: typeof Divider;
    wrapper: typeof Wrapper;
    spacer: typeof Spacer;
    raw: typeof Raw;
    accordion: typeof Accordion;
    "accordion-element": typeof AccordionElement;
    "accordion-title": typeof AccordionTitle;
    "accordion-text": typeof AccordionText;
    carousel: typeof Carousel;
    hero: typeof Hero;
    navbar: typeof Navbar;
    social: typeof Social;
    table: typeof Table;
    advanced_text: typeof Text;
    advanced_image: typeof Image;
    advanced_button: typeof Button;
    advanced_divider: typeof Divider;
    advanced_spacer: typeof Spacer;
    advanced_accordion: typeof Accordion;
    advanced_carousel: typeof Carousel;
    advanced_navbar: typeof Navbar;
    advanced_social: typeof Social;
    advanced_hero: typeof Hero;
    advanced_wrapper: typeof Wrapper;
    advanced_section: typeof Section;
    advanced_group: typeof Group;
    advanced_column: typeof Column;
};
