import { IPage } from './Page';
import { ISection } from './Section';
import { IColumn } from './Column';
import { IText } from './Text';
import { IImage } from './Image';
import { IGroup } from './Group';
import { IButton } from './Button';
import { IDivider } from './Divider';
import { IWrapper } from './Wrapper';
import { ISpacer } from './Spacer';
import { ICarousel } from './Carousel';
import { IHero } from './Hero';
import { INavbar } from './Navbar';
import { ISocial } from './Social';
import { IRaw } from './Raw';
import { ITemplate } from './Template';
import { IAccordion } from './Accordion';
import { IAccordionElement } from './AccordionElement';
import { IAccordionTitle } from './AccordionTitle';
import { IAccordionText } from './AccordionText';
import { ITable } from './Table';
export declare const standardBlocks: {
    page: import("../..").IBlock<IPage>;
    section: import("../..").IBlock<ISection>;
    column: import("../..").IBlock<IColumn>;
    text: import("../..").IBlock<IText>;
    image: import("../..").IBlock<IImage>;
    group: import("../..").IBlock<IGroup>;
    button: import("../..").IBlock<IButton>;
    divider: import("../..").IBlock<IDivider>;
    wrapper: import("../..").IBlock<IWrapper>;
    spacer: import("../..").IBlock<ISpacer>;
    raw: import("../..").IBlock<IRaw>;
    carousel: import("../..").IBlock<ICarousel>;
    hero: import("../..").IBlock<IHero>;
    navbar: import("../..").IBlock<INavbar>;
    social: import("../..").IBlock<ISocial>;
    template: import("../..").IBlock<ITemplate>;
    accordion: import("../..").IBlock<IAccordion>;
    "accordion-element": import("../..").IBlock<IAccordionElement>;
    "accordion-title": import("../..").IBlock<import("../..").IBlockData<any, any>>;
    "accordion-text": import("../..").IBlock<import("../..").IBlockData<any, any>>;
    table: import("../..").IBlock<ITable>;
};
export type { IPage, ISection, IWrapper, IColumn, IGroup, IText, ITable, IImage, IButton, IDivider, ISpacer, ICarousel, IHero, ISocial, INavbar, IRaw, IAccordion, IAccordionElement, IAccordionTitle, IAccordionText, ITemplate, };
